# Generated by Django 5.2.1 on 2025-05-27 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PAP', 'Papel y cartón'), ('PLAS', 'Plásticos reciclables'), ('VID', 'Vidrios'), ('LAT', 'Latas'), ('ELEC', 'Electrónicos pequeños'), ('TEX', 'Textiles'), ('VOL', 'Voluminosos reciclables')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_estimada', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('RUT', 'En ruta'), ('COM', 'Completada')], default='PEN', max_length=3)),
                ('comentario_operario', models.TextField(blank=True, null=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
